# Generated by Django 5.2.5 on 2026-06-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctor_business_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city_or_block',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_mode',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('both', 'Online and Offline')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_emergency_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='village_or_area',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
