# Generated by Django 5.2.12 on 2026-06-12 03:55

from django.db import migrations, models


def remove_duplicate_slot_appointments(apps, schema_editor):
    Appointment = apps.get_model("appointments", "Appointment")
    Availability = apps.get_model("doctors", "Availability")

    duplicate_slot_ids = (
        Appointment.objects.values_list("availability_id", flat=True)
        .exclude(availability_id=None)
        .order_by("availability_id")
        .distinct()
    )

    status_priority = {
        "confirmed": 0,
        "pending": 1,
        "cancelled": 2,
    }

    for slot_id in duplicate_slot_ids:
        appointments = list(Appointment.objects.filter(availability_id=slot_id).order_by("id"))
        if len(appointments) <= 1:
            continue

        appointments.sort(
            key=lambda appointment: (
                status_priority.get(appointment.status, 99),
                -appointment.id,
            )
        )
        keep = appointments[0]
        Appointment.objects.filter(
            availability_id=slot_id,
        ).exclude(id=keep.id).delete()

        Availability.objects.filter(id=slot_id).update(is_booked=keep.status != "cancelled")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_pharmacy_role'),
        ('appointments', '0002_align_appointment_flow'),
        ('doctors', '0006_doctor_city_or_block_doctor_consultation_mode_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_slot_appointments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('availability',), name='unique_appointment_per_availability'),
        ),
    ]
