# Generated by Django 5.2.12 on 2026-06-11 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=180)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('phone_no', models.CharField(blank=True, max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=80)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city_or_block', models.CharField(blank=True, max_length=100)),
                ('village_or_area', models.CharField(blank=True, max_length=120)),
                ('full_address', models.TextField(blank=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_open_now', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=180)),
                ('brand_name', models.CharField(blank=True, max_length=180)),
                ('strength', models.CharField(blank=True, max_length=80)),
                ('form', models.CharField(blank=True, max_length=80)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('prescription_required', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacies.pharmacy')),
            ],
            options={
                'ordering': ['medicine_name'],
            },
        ),
    ]
